# Generated by Django 3.2.5 on 2021-07-26 03:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 7, 26, 3, 30, 28, 306097, tzinfo=utc))),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
