# Generated by Django 3.2.5 on 2021-07-26 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 5, 2, 16, 594902, tzinfo=utc)),
        ),
    ]
